language: d

d:
  #- dmd
  - dmd-2.067.1
  - dmd-2.067.0
  - dmd-2.066.1
  - dmd-2.065.0
  - ldc-0.15.1
  #- gdc-4.9.2 hangs forever in pong build

script:
  - dub test --compiler=$DC || exit 1
  - cd samples/pong/
  - dub build --compiler=$DC

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aec3459262a3eafcd684
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
