language: d

sudo: false

d:
  - dmd #-2.071.0
  - dmd-2.070.2
  - dmd-2.069.2
  #- dmd-2.068.2 broken due to dmd internal assert (crash)
  - dmd-2.067.1
  - ldc-1.0.0-beta1
  - ldc #-0.17.0
  - ldc-0.16.1
  - gdc #-5.2.0

script:
  - dub test --compiler=$DC || exit 1
  - cd samples/helloworld/
  - dub build --compiler=$DC
  - cd ../pong/
  - dub build --compiler=$DC

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aec3459262a3eafcd684
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
